/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[flyway_schema_history]
(
[installed_rank] [int] NOT NULL,
[version] [nvarchar] (50) NULL,
[description] [nvarchar] (200) NULL,
[type] [nvarchar] (20) NOT NULL,
[script] [nvarchar] (1000) NOT NULL,
[checksum] [int] NULL,
[installed_by] [nvarchar] (100) NOT NULL,
[installed_on] [datetime] NOT NULL CONSTRAINT [DF__flyway_sc__insta__5CD6CB2B] DEFAULT (getdate()),
[execution_time] [int] NOT NULL,
[success] [bit] NOT NULL
)
GO
ALTER TABLE [dbo].[flyway_schema_history] ADD CONSTRAINT [flyway_schema_history_pk] PRIMARY KEY CLUSTERED ([installed_rank])
GO
CREATE NONCLUSTERED INDEX [flyway_schema_history_s_idx] ON [dbo].[flyway_schema_history] ([success])
GO
