/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Sales]
(
[TransactionId] [smallint] NOT NULL IDENTITY(1, 1),
[CustomerId] [smallint] NULL,
[Net Amount] [int] NULL,
[Completed] [bit] NULL
)
GO
